plugins {
    id 'java'
    id 'application'
}

group = 'ch.bzz'
version = '1.0-SNAPSHOT'

application {
    mainClass = 'ch.bzz.LibraryAppMain'
}

tasks.register('runApi', JavaExec) {
    group = 'application'
    description = 'Runs the Javalin API on port 7070'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'ch.bzz.JavalinMain'
}

repositories {
    mavenCentral()
}

dependencies {
    // dependencies for the application
    implementation 'io.javalin:javalin:6.7.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.17.2'
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'
    implementation 'org.postgresql:postgresql:42.7.3'
    implementation 'io.jsonwebtoken:jjwt-api:0.12.7'

    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.7'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.7'

    // dependencies for testing
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

test {
    useJUnitPlatform()
}
